In [1]:
# 读取2.csv
import pandas as pd
data=pd.read_excel('3.xls', header=None)

rows = []
# Skip the header row (row 0) 
for idx, row in data.iloc[1:].iterrows():
    date = row[0]
    weather = row[1]
    temp = row[2]
    wind = row[3]
    weather_day, weather_night = weather.split('/')
    temp_day, temp_night = temp.split('/')
    wind_day, wind_night = wind.split('/')

    rows.append([date, '白天', weather_day.strip(), temp_day.strip(), wind_day.strip()])
    rows.append([date, '夜间', weather_night.strip(), temp_night.strip(), wind_night.strip()])

# 构建DataFrame
df = pd.DataFrame(rows, columns=['日期', '时间段', '天气状况', '气温', '风力风向'])
#气温删掉℃符号 , 白天是0 ,夜晚是1
df['气温'] = df['气温'].str.replace('℃', '').astype(float)
df['时间段'] = df['时间段'].map({'白天': 0, '夜间': 1})
df.to_csv('3分.csv', index=False, encoding='utf-8-sig')

In [7]:
#合并表2,3
data2 = pd.read_excel('2.xls')
data3 = pd.read_excel('3.xls')
# 合并数据
merged_data = pd.concat([data2, data3], ignore_index=True) 
# 保存合并后的数据
merged_data.to_csv('合并23.csv', index=False, encoding='utf-8-sig')

In [11]:
#删除合并后的数据中重复的行
merged_data= pd.read_csv('合并23.csv')
merged_data.drop_duplicates(inplace=True)
# 保存删除重复行后的数据
merged_data.to_csv('合并23去重.csv', index=False, encoding='utf-    8-sig')

In [14]:
# 读取合并.csv
import pandas as pd
data=pd.read_csv('合并23去重.csv', encoding='utf-8-sig')

rows = []
# Skip the header row (row 0) 
for idx, row in data.iloc[1:].iterrows():
    date = row[0]
    weather = row[1]
    temp = row[2]
    wind = row[3]
    weather_day, weather_night = weather.split('/')
    temp_day, temp_night = temp.split('/')
    wind_day, wind_night = wind.split('/')

    rows.append([date, '白天', weather_day.strip(), temp_day.strip(), wind_day.strip()])
    rows.append([date, '夜间', weather_night.strip(), temp_night.strip(), wind_night.strip()])

# 构建DataFrame
df = pd.DataFrame(rows, columns=['日期', '时间段', '天气状况', '气温', '风力风向'])
#气温删掉℃符号 , 白天是0 ,夜晚是1
df['气温'] = df['气温'].str.replace('℃', '').astype(float)
df['时间段'] = df['时间段'].map({'白天': 0, '夜间': 1})
df.to_csv('23分.csv', index=False, encoding='utf-8-sig')

C:\Users\金田泉\AppData\Local\Temp\ipykernel_20964\1252753701.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  date = row[0]
C:\Users\金田泉\AppData\Local\Temp\ipykernel_20964\1252753701.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  weather = row[1]
C:\Users\金田泉\AppData\Local\Temp\ipykernel_20964\1252753701.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp = row[2]
C:\Users\金田泉\AppData\Local\Temp\ipykernel_20964\1252753701.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  wind = row[3]

In [27]:
import pandas as pd

# 定义映射字典
wind_direction_map = {
    '北风': 0,
    '东北风': 1,
    '东风': 2,
    '东南风': 3,
    '南风': 4,
    '西南风': 5,
    '西风': 6,
    '西北风': 7,
    '无持续风向': 8,
    '旋转风': 9
}

wind_power_map = {
    '微风': 0,
    '≤3级': 1,
    '3-4级': 2,
    '4-5级': 3,
    '5-6级': 4
}

def encode_wind_info(wind_str):
    parts = wind_str.strip().split()
    if len(parts) < 2:
        return -1, -1

    direction = parts[0]
    power = ' '.join(parts[1:])

    dir_code = wind_direction_map.get(direction, -1)
    power_code = wind_power_map.get(power, -1)

    return dir_code, power_code

# 示例 DataFrame
data = pd.read_csv('23分.csv', encoding='utf-8-sig')

df = pd.DataFrame(data, columns=['日期', '时间段', '天气状况', '气温', '风力风向'])

# 应用编码函数
df[['风向编码', '风力编码']] = df['风力风向'].apply(lambda x: pd.Series(encode_wind_info(x)))

df

             日期  时间段  天气状况    气温      风力风向  风向编码  风力编码
0      2011/1/2    0    小雪   0.0    旋转风 微风     9     0
1      2011/1/2    1     阴  -6.0  无持续风向 微风     8     0
2      2011/1/3    0     阴   0.0    旋转风 微风     9     0
3      2011/1/3    1    多云  -5.0  无持续风向 微风     8     0
4      2011/1/4    0     阴   0.0    旋转风 微风     9     0
...         ...  ...   ...   ...       ...   ...   ...
1929  2013/8/26    1    多云  25.0   西南风 ≤3级     5     1
1930  2013/8/27    0     阴  31.0    东风 ≤3级     2     1
1931  2013/8/27    1  小到中雨  24.0    南风 ≤3级     4     1
1932  2013/8/28    0  小到中雨  25.0    西风 ≤3级     6     1
1933  2013/8/28    1     阴  20.0    东风 ≤3级     2     1

[1934 rows x 7 columns]

In [26]:
df

             日期  时间段  天气状况    气温      风力风向  降水强度 天气主类别
0      2011/1/2    0    小雪   0.0    旋转风 微风     1     雪
1      2011/1/2    1     阴  -6.0  无持续风向 微风     0     阴
2      2011/1/3    0     阴   0.0    旋转风 微风     0     阴
3      2011/1/3    1    多云  -5.0  无持续风向 微风     0    多云
4      2011/1/4    0     阴   0.0    旋转风 微风     0     阴
...         ...  ...   ...   ...       ...   ...   ...
1929  2013/8/26    1    多云  25.0   西南风 ≤3级     0    多云
1930  2013/8/27    0     阴  31.0    东风 ≤3级     0     阴
1931  2013/8/27    1  小到中雨  24.0    南风 ≤3级     1     雨
1932  2013/8/28    0  小到中雨  25.0    西风 ≤3级     1     雨
1933  2013/8/28    1     阴  20.0    东风 ≤3级     0     阴

[1934 rows x 7 columns]

In [28]:
import pandas as pd

# 步骤 1: 创建一个模拟您的数据的 DataFrame
# 在实际应用中，您会使用 pd.read_csv() 或 pd.read_excel() 来读取您的文件

print("=============== 1. 原始数据 ===============")
print(df)
print("\n" + "="*50 + "\n")


# 步骤 2: 数据清洗与特征工程
# 我们的目标是根据'天气状况'创建更有意义的新特征。

# 2.1 创建一个有序特征：“降水强度”
# 这是一个典型的“序号编码”场景，因为强度有明确的大小顺序。
# 0:无降水, 1:小量, 2:中量, 3:大量, 4:超大量
precip_intensity_map = {
    '晴': 0, '多云': 0, '阴': 0, '雾': 0, '浮尘': 0,
    '小雨': 1, '阵雨': 1, '小雪': 1, '雨夹雪': 1, '小到中雨': 1,
    '中雨': 2, '中雪': 2, '小到中雪': 2,
    '大雨': 3, '大雪': 3, '中到大雨': 3,
    '雷阵雨': 3, # 雷阵雨通常强度较大
    '大到暴雨': 4
}
# 使用 .map() 应用映射，对于任何未在map中定义的天气（如果存在），用0填充
df['降水强度'] = df['天气状况'].map(precip_intensity_map).fillna(0).astype(int)


# 2.2 创建一个简化的天气主类别，用于后续的“独热编码”
# 这里我们将相似的天气现象归为一类，以减少最终特征的维度。
simplify_category_map = {
    '晴': '晴', 
    '多云': '多云', 
    '阴': '阴',
    '雾': '雾霾沙尘', 
    '浮尘': '雾霾沙尘',
    '小雨': '雨', '阵雨': '雨', '小到中雨': '雨', '中雨': '雨', 
    '中到大雨': '雨', '大雨': '雨', '雷阵雨': '雨', '大到暴雨': '雨',
    '小雪': '雪', '中雪': '雪', '大雪': '雪', '雨夹雪': '雪', '阵雪': '雪', '小到中雪': '雪'
}
df['天气主类别'] = df['天气状况'].map(simplify_category_map).fillna('其他')


print("=============== 2. 特征工程后的数据 ===============")
print("增加了'降水强度' (有序) 和 '天气主类别' (无序) 两列")
print(df)
print("\n" + "="*50 + "\n")


# 步骤 3: 对无序类别执行独热编码 (One-Hot Encoding)
# 我们对刚刚创建的“天气主类别”进行独热编码
# pd.get_dummies() 是一个非常方便的函数
one_hot_df = pd.get_dummies(df['天气主类别'], prefix='天气', dtype=int)

print("=============== 3. 对'天气主类别'进行独热编码的结果 ===============")
print(one_hot_df)
print("\n" + "="*50 + "\n")


# 步骤 4: 合并所有特征，形成最终可用于建模的数据集
# 将原始数据、有序特征、独热编码特征合并在一起
final_df = pd.concat([df, one_hot_df], axis=1)

# 现在，我们可以删除掉临时的和原始的文本列，只保留对模型有用的数值特征
model_ready_df = final_df.drop(['天气状况', '天气主类别'], axis=1)

print("=============== 4. 最终可用于建模的数据 ===============")
print("这是输入到污染物分析或天气预测模型中的最终数据形态")
final_df

=============== 1. 原始数据 ===============
             日期  时间段  天气状况    气温      风力风向  风向编码  风力编码
0      2011/1/2    0    小雪   0.0    旋转风 微风     9     0
1      2011/1/2    1     阴  -6.0  无持续风向 微风     8     0
2      2011/1/3    0     阴   0.0    旋转风 微风     9     0
3      2011/1/3    1    多云  -5.0  无持续风向 微风     8     0
4      2011/1/4    0     阴   0.0    旋转风 微风     9     0
...         ...  ...   ...   ...       ...   ...   ...
1929  2013/8/26    1    多云  25.0   西南风 ≤3级     5     1
1930  2013/8/27    0     阴  31.0    东风 ≤3级     2     1
1931  2013/8/27    1  小到中雨  24.0    南风 ≤3级     4     1
1932  2013/8/28    0  小到中雨  25.0    西风 ≤3级     6     1
1933  2013/8/28    1     阴  20.0    东风 ≤3级     2     1

[1934 rows x 7 columns]

==================================================

=============== 2. 特征工程后的数据 ===============
增加了'降水强度' (有序) 和 '天气主类别' (无序) 两列
             日期  时间段  天气状况    气温      风力风向  风向编码  风力编码  降水强度 天气主类别
0      2011/1/2    0    小雪   0.0    旋转风 微风     9     0     1     雪
1      2011/1/2    1     阴  -6.0  无持续风向 微风     8     0     0     阴
2      2011/1/3    0     阴   0.0    旋转风 微风     9     0     0     阴
3      2011/1/3    1    多云  -5.0  无持续风向 微风     8     0     0    多云
4      2011/1/4    0     阴   0.0    旋转风 微风     9     0     0     阴
...         ...  ...   ...   ...       ...   ...   ...   ...   ...
1929  2013/8/26    1    多云  25.0   西南风 ≤3级     5     1     0    多云
1930  2013/8/27    0     阴  31.0    东风 ≤3级     2     1     0     阴
1931  2013/8/27    1  小到中雨  24.0    南风 ≤3级     4     1     1     雨
1932  2013/8/28    0  小到中雨  25.0    西风 ≤3级     6     1     1     雨
1933  2013/8/28    1     阴  20.0    东风 ≤3级     2     1     0     阴

[1934 rows x 9 columns]

==================================================

=============== 3. 对'天气主类别'进行独热编码的结果 ===============
      天气_多云  天气_晴  天气_阴  天气_雨  天气_雪  天气_雾霾沙尘
0         0     0     0     0     1        0
1         0     0     1     0     0        0
2         0     0     1     0     0        0
3         1     0     0     0     0        0
4         0     0     1     0     0        0
...     ...   ...   ...   ...   ...      ...
1929      1     0     0     0     0        0
1930      0     0     1     0     0        0
1931      0     0     0     1     0        0
1932      0     0     0     1     0        0
1933      0     0     1     0     0        0

[1934 rows x 6 columns]

==================================================

=============== 4. 最终可用于建模的数据 ===============
这是输入到污染物分析或天气预测模型中的最终数据形态

,日期,时间段,天气状况,气温,风力风向,风向编码,风力编码,降水强度,天气主类别,天气_多云,天气_晴,天气_阴,天气_雨,天气_雪,天气_雾霾沙尘
0,2011/1/2,0,小雪,0.0,旋转风 微风,9,0,1,雪,0,0,0,0,1,0
1,2011/1/2,1,阴,-6.0,无持续风向 微风,8,0,0,阴,0,0,1,0,0,0
2,2011/1/3,0,阴,0.0,旋转风 微风,9,0,0,阴,0,0,1,0,0,0
3,2011/1/3,1,多云,-5.0,无持续风向 微风,8,0,0,多云,1,0,0,0,0,0
4,2011/1/4,0,阴,0.0,旋转风 微风,9,0,0,阴,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929,2013/8/26,1,多云,25.0,西南风 ≤3级,5,1,0,多云,1,0,0,0,0,0
1930,2013/8/27,0,阴,31.0,东风 ≤3级,2,1,0,阴,0,0,1,0,0,0
1931,2013/8/27,1,小到中雨,24.0,南风 ≤3级,4,1,1,雨,0,0,0,1,0,0
1932,2013/8/28,0,小到中雨,25.0,西风 ≤3级,6,1,1,雨,0,0,0,1,0,0
1933,2013/8/28,1,阴,20.0,东风 ≤3级,2,1,0,阴,0,0,1,0,0,0

In [ ]:
# 删掉'天气状况','风力风向','天气主类别'列
final_df = final_df.drop(['天气状况', '风力风向', '天气主类别'], axis=1)

KeyError: "['天气状况', '风力风向', '天气主类别'] not found in axis"

In [32]:

# 保存最终的 DataFrame
final_df.to_csv('合并23最终数据编码.csv', index=False, encoding='utf-8-sig')