In [ ]:
# 读取2.csv
import pandas as pd
data=pd.read_excel('2.xls', header=None)

rows = []
# Skip the header row (row 0) 
for idx, row in data.iloc[1:].iterrows():
    date = row[0]
    weather = row[1]
    temp = row[2]
    wind = row[3]
    weather_day, weather_night = weather.split('/')
    temp_day, temp_night = temp.split('/')
    wind_day, wind_night = wind.split('/')

    rows.append([date, '白天', weather_day.strip(), temp_day.strip(), wind_day.strip()])
    rows.append([date, '夜间', weather_night.strip(), temp_night.strip(), wind_night.strip()])

# 构建DataFrame
df = pd.DataFrame(rows, columns=['日期', '时间段', '天气状况', '气温', '风力风向'])
df

            日期 时间段  天气状况   气温     风力风向
0   2013-04-01  白天    多云  21℃  西南风 ≤3级
1   2013-04-01  夜间    多云   9℃  东北风 ≤3级
2   2013-04-02  白天     阴  19℃   南风 ≤3级
3   2013-04-02  夜间     阴  10℃   西风 ≤3级
4   2013-04-03  白天    多云  22℃  东北风 ≤3级
..         ...  ..   ...  ...      ...
295 2013-08-26  夜间    多云  25℃  西南风 ≤3级
296 2013-08-27  白天     阴  31℃   东风 ≤3级
297 2013-08-27  夜间  小到中雨  24℃   南风 ≤3级
298 2013-08-28  白天  小到中雨  25℃   西风 ≤3级
299 2013-08-28  夜间     阴  20℃   东风 ≤3级

[300 rows x 5 columns]

In [8]:
#气温删掉℃符号 , 白天是0 ,夜晚是1
df['气温'] = df['气温'].str.replace('℃', '').astype(float)
df['时间段'] = df['时间段'].map({'白天': 0, '夜间': 1})
df

            日期  时间段  天气状况    气温     风力风向
0   2013-04-01    0    多云  21.0  西南风 ≤3级
1   2013-04-01    1    多云   9.0  东北风 ≤3级
2   2013-04-02    0     阴  19.0   南风 ≤3级
3   2013-04-02    1     阴  10.0   西风 ≤3级
4   2013-04-03    0    多云  22.0  东北风 ≤3级
..         ...  ...   ...   ...      ...
295 2013-08-26    1    多云  25.0  西南风 ≤3级
296 2013-08-27    0     阴  31.0   东风 ≤3级
297 2013-08-27    1  小到中雨  24.0   南风 ≤3级
298 2013-08-28    0  小到中雨  25.0   西风 ≤3级
299 2013-08-28    1     阴  20.0   东风 ≤3级

[300 rows x 5 columns]

In [10]:
# 保存为新的Excel文件
df.to_csv('2分.csv', index=False, header=False)